### ISSUE TITLE
More Progress with Project Idea

### ISSUE THREAD

**Issue by oliver-gomes** [zero-to-mastery/ZtM-Workouts#9]
@SamirJouni I would also work on a project here as Thijs suggested but working on React would be amazing idea so if it's a yes, React need the repo name changed to lowercase.

**Comment by sophiabrandt** [comment]
@oliver-gomes Are you still interested in this?
If so, I am not sure what you need to continue. Can you please make a pull request with the suggested changes?

**Comment by oliver-gomes** [comment]
Closing this out as this is super old
